### ISSUE TITLE
Misassembly of environment Components in JSON String

### ISSUE THREAD

**Issue by bobmor99** [SignalK/signalk-multiplexer-node#9] opened 2015-03-08 15:35 UTC
I could be wrong that the problem lies with the multiplexer repo and that there is a problem with the JSON string but I observed the problem in both instrumentpanel and simplegauges.

Using n2k-from-file, nmea-from-file, instrumentpanel, simplegauges, and DBT (depth below transducer) to illustrate.

------------------------------
bin/n2k-from-file:  (no problems here)
 -instrumentpanel shows cell labeled "environment.depth.belowTransducer" containing a depth value
 -simplegauges shows a functioning depth gauge
 -from api/v1

```
{
  "environment": {
    "depth": {
      "belowTransducer": {
        "value": 42.26,
        "source": {
          "label": "",
          "type": "NMEA2000",
          "pgn": 128267,
          "src": 115
        },
        "timestamp": "2014-08-15-16:00:08.066"
      }
    },
    "date": {
      "value": "2014.08.15",
      "source": {
        "label": "",
        "type": "NMEA2000",
        "pgn": 126992,
        "src": 160
      },
      "timestamp": "2014-08-15-16:00:08.377"
    },
    "time": {
      "value": "16:00:07.07570",
      "source": {
        "label": "",
        "type": "NMEA2000",
        "pgn": 126992,
        "src": 160
      },
      "timestamp": "2014-08-15-16:00:08.377"
    },
    "wind": {
      "speedApparent": {
        "value": 10.86,
        "source": {
          "label": "",
          "type": "NMEA2000",
          "pgn": 130306,
          "src": 115
        },
        "timestamp": "2014-08-15-16:00:08.434"
      },
      "angleApparent": {
        "value": 47,
        "source": {
          "label": "",
          "type": "NMEA2000",
          "pgn": 130306,
          "src": 115
        },
        "timestamp": "2014-08-15-16:00:08.434"
      }
    }
  }
}
```

-------------------------------
bin/nmea-from-file:
 -instrumentpanel shows cell labeled "environment.depth" containing the string "[object Object]"
 -simplegauges shows a non-functioning depth gauge, i.e. it remains stuck at zero.
 -from api/v1

```
{
  "environment": {
    "wind": {
      "angleApparent": {
        "timestamp": "2015-04-08T15:24:30.000Z",
        "source": {
          "type": "NMEA0183",
          "src": "MWV",
          "label": "signalk-parser-nmea0183"
        },
        "value": -13
      },
      "speedApparent": {
        "timestamp": "2015-04-08T15:24:30.000Z",
        "source": {
          "type": "NMEA0183",
          "src": "MWV",
          "label": "signalk-parser-nmea0183"
        },
        "value": 7.299968515992024
      },
      "source": {},
      "timestamp": "2015-03-08T15:24:30.628Z",
      "angleTrue": {
        "timestamp": "2015-04-08T15:24:29.000Z",
        "source": {
          "type": "NMEA0183",
          "src": "MWV",
          "label": "signalk-parser-nmea0183"
        },
        "value": -22
      },
      "speedTrue": {
        "timestamp": "2015-04-08T15:24:29.000Z",
        "source": {
          "type": "NMEA0183",
          "src": "MWV",
          "label": "signalk-parser-nmea0183"
        },
        "value": 4.367634439800725
      }
    },
    "depth": {
      "belowTransducer": {
        "source": {
          "type": "NMEA0183",
          "src": "DBT",
          "label": "signalk-parser-nmea0183"
        },
        "timestamp": "2015-04-08T15:24:30.000Z",
        "value": 13.36
      },
      "source": {},
      "timestamp": "2015-03-08T15:24:30.126Z"
    }
  }
}
```

**Comment by tkurki** [comment] 2015-03-08 16:38
I believe the root cause is https://github.com/SignalK/signalk-parser-nmea0183/issues/24, closing as duplicate.

**Closed by tkurki** 2015-03-08 16:38 UTC
